name: Code Quality Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 -r requirements.txt
    
    # Adjust the path accordingly if pydevtools is in a subdirectory
    - name: Run pylint
      run: |
        pylint pydevtools
    
    # Adjust the path accordingly if pydevtools is in a subdirectory
    - name: Run flake8
      run: |
        flake8 pydevtools
        
